import type { VehicleRecord } from '@/types/domain'

export const FLEET: VehicleRecord[] = [
  {
    id: 'sedan',
    name: 'Sedan',
    type: 'Sedan',
    passenger_capacity: 3,
    luggage_capacity: '2 large + 2 small',
    description: 'Comfortable sedan for city transfers and short trips. Ideal for couples or small groups with standard luggage.',
    photos: ['/Fleet/sedan1.jpg', '/Fleet/sedan2.jpg', '/Fleet/sedan3.jpg'],
    availability_status: 'available',
    internal_notes: null,
    active: true,
  },
  {
    id: 'voxy',
    name: 'Toyota Voxy',
    type: 'MPV',
    passenger_capacity: 7,
    luggage_capacity: '4 large',
    description: 'Spacious 7-seater van perfect for families and small groups.',
    photos: ['/Fleet/voxy1.jpg', '/Fleet/voxy2.jpg', '/Fleet/voxy3.jpg'],
    availability_status: 'available',
    internal_notes: null,
    active: true,
  },
  {
    id: 'kdh-standard',
    name: 'Toyota KDH Standard Roof',
    type: 'Van',
    passenger_capacity: 10,
    luggage_capacity: '8 large',
    description: 'High-capacity standard-roof van for groups with generous luggage space.',
    photos: ['/Fleet/flatroof1.jpg', '/Fleet/flatroof2.jpg', '/Fleet/flatroof3.jpg'],
    availability_status: 'available',
    internal_notes: null,
    active: true,
  },
  {
    id: 'kdh-high',
    name: 'Toyota KDH High Roof',
    type: 'Van',
    passenger_capacity: 12,
    luggage_capacity: '10 large',
    description: 'Standing-height high roof van for maximum comfort on longer journeys.',
    photos: ['/Fleet/highroof1.jpg', '/Fleet/highroof2.jpg', '/Fleet/highroof3.jpg'],
    availability_status: 'available',
    internal_notes: null,
    active: true,
  },
  {
    id: 'suv',
    name: 'SUV',
    type: 'SUV',
    passenger_capacity: 5,
    luggage_capacity: '4 large',
    description: 'Premium SUV for couples and small families.',
    photos: ['/Fleet/sedan1.jpg', '/Fleet/sedan2.jpg'],
    availability_status: 'available',
    internal_notes: null,
    active: true,
  },
]
